spring:
  application:
    name: customer
  mvc:
    servlet:
      path: /
      load-on-startup: 1
      multipart:
        max-file-size: 500MB
        max-request-size: 500MB
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  servlet:
    session:
      cookie:
        name: CUSTOMER_SESSION
        path: /
        max-age: 864000
      timeout: 20160


api:
  base-url: http://localhost:8081
